syntax_analysis:
  grammar_file: "../data/grammar-trained.pcfg"
  input: "../data/recurrence_sentences/epileptic_eeg_dataset/sentence_converted/normal_integrated_all_d2_s4_converted_retained.txt"
  repetition: "../data/recurrence_sentences/epileptic_eeg_dataset/sentence_converted/normal_integrated_all_d2_s4_converted_retained_repetition.txt"
  log_intervals: 1000000
  log_path: "/data1/pcfg-log/logs/normal-test/"
  report_path: "/data1/pcfg-log/reports/normal-test/"
  serialize_to_files: true
  tree_serialization_path: "/data1/pcfg-log/serialized_tree/normal-test/"
  report_statistics: false
  sentence_from: -1
  sentence_to: -1
