main:
  grammar_file: "../../data/pcfg/grammar_log_partition_1_epoch_3.pcfg"
  input:  "../../data/recurrence_sentences/epileptic_eeg_dataset/validate_sentences.txt"
  log_intervals: -1
  log_path: "data/logs/"
  log_f:
    enabled: false
    intervals: -1
  log_warning_in_training: false
  batch_size_for_parameter_update: -1
  split_data:
    enabled: false
    val_dataset_path: "../../data/recurrence_sentences/epileptic_eeg_dataset/validate_sentences.txt" 
    train_dataset_path: "../../data/recurrence_sentences/epileptic_eeg_dataset/train_sentences.txt"
    train_fraction: 0.8
  n_epochs: 1
  limit_n_sentences: -1
  validation_only: true
